import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'getting-started',
    'installation',
    {
      type: 'category',
      label: 'Categories',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'API Categories',
        description: 'Browse TypeScript utility functions organized by category.',
        slug: '/categories',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'categories',
        },
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      collapsible: true,
      collapsed: true,
      items: [
        'comparisons/radashi',
        'comparisons/alternatives',
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      collapsible: true,
      collapsed: true,
      items: [
        'legal/license',
        'legal/open-source-libraries',
        'legal/website-dependencies',
      ],
    },
  ],
};

export default sidebars;
