import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'getting-started',
    'installation',
    {
      type: 'category',
      label: 'Array',
      collapsed: false,
      link: { type: 'doc', id: 'categories/array/index' },
      items: [
        'categories/array/arrayEquals',
        'categories/array/chunk',
        'categories/array/deepCompare',
        'categories/array/difference',
        'categories/array/intersection',
        'categories/array/oneInCommon',
        'categories/array/quickCompare',
        'categories/array/sort',
        'categories/array/unique',
      ],
    },
    {
      type: 'category',
      label: 'Date',
      collapsed: false,
      link: { type: 'doc', id: 'categories/date/index' },
      items: [
        'categories/date/compare',
        'categories/date/difference',
        'categories/date/format',
        'categories/date/is',
        'categories/date/safeDate',
        'categories/date/timestamp',
      ],
    },
    {
      type: 'category',
      label: 'Function',
      collapsed: false,
      link: { type: 'doc', id: 'categories/function/index' },
      items: [
        'categories/function/debounce',
        'categories/function/isDefinedAndNotNull',
        'categories/function/memoize',
        'categories/function/returnOrThrowError',
        'categories/function/throttle',
      ],
    },
    {
      type: 'category',
      label: 'Number',
      collapsed: false,
      link: { type: 'doc', id: 'categories/number/index' },
      items: [
        'categories/number/clamp',
        'categories/number/random',
        'categories/number/roundTo',
      ],
    },
    {
      type: 'category',
      label: 'Object',
      collapsed: false,
      link: { type: 'doc', id: 'categories/object/index' },
      items: [
        'categories/object/deepClone',
        'categories/object/deepCompare',
        'categories/object/deepMerge',
        'categories/object/get',
        'categories/object/quickCompare',
        'categories/object/removeUndefinedNull',
        'categories/object/set',
      ],
    },
    {
      type: 'category',
      label: 'Observable',
      collapsed: false,
      link: { type: 'doc', id: 'categories/observable/index' },
      items: [
        'categories/observable/combine',
        'categories/observable/combineLatest',
      ],
    },
    {
      type: 'category',
      label: 'Promise',
      collapsed: false,
      link: { type: 'doc', id: 'categories/promise/index' },
      items: [
        'categories/promise/consoleLogPromise',
        'categories/promise/delay',
        'categories/promise/falsyPromiseOrThrow',
        'categories/promise/meaningPromiseOrThrow',
        'categories/promise/retry',
        'categories/promise/truthyPromiseOrThrow',
      ],
    },
    {
      type: 'category',
      label: 'String',
      collapsed: false,
      link: { type: 'doc', id: 'categories/string/index' },
      items: [
        'categories/string/camelCase',
        'categories/string/capitalize',
        'categories/string/errorToReadableMessage',
        'categories/string/kebabCase',
        'categories/string/labelize',
      ],
    },
    {
      type: 'category',
      label: 'Type',
      collapsed: false,
      link: { type: 'doc', id: 'categories/type/index' },
      items: [
        'categories/type/isEmpty',
        'categories/type/isSpecialObject',
        'categories/type/typeChecks',
      ],
    },
    {
      type: 'category',
      label: 'URL',
      collapsed: false,
      link: { type: 'doc', id: 'categories/url/index' },
      items: [
        'categories/url/cleanPath',
        'categories/url/extractPureURI',
        'categories/url/onlyPath',
        'categories/url/relativeURLToAbsolute',
        'categories/url/withLeadingSlash',
        'categories/url/withTrailingSlash',
        'categories/url/withoutLeadingSlash',
        'categories/url/withoutTrailingSlash',
      ],
    },
    {
      type: 'category',
      label: 'Version',
      collapsed: false,
      link: { type: 'doc', id: 'categories/version/index' },
      items: [
        'categories/version/compare',
        'categories/version/increment',
        'categories/version/parse',
        'categories/version/satisfiesRange',
        'categories/version/stripV',
      ],
    },
  ],
};

export default sidebars;
