import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Features',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'features' },
      ],
    },
  ],
};

export default sidebars;
