import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Features',
          collapsible: true,
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'features' },
          ],
        },
        'reference/contributing',
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      collapsible: true,
      collapsed: true,
      items: [
        'legal/license',
        'legal/open-source-libraries',
      ],
    },
  ],
};

export default sidebars;
